Permissions are defined programmatically.

~~~js
// *.telefunc.js
// Environment: Node.js

import { getContext, Abort } from 'telefunc'

export { deletePost }

async function deletePost() {
  // See Authentication guide for an introduction about `getContext()`.
  const context = getContext()

  // Only admins are allowed to remove posts
  if( !context.user.isAdmin ) {
    // The user is not an admin — we abort.
    throw new Abort()
  }

  // ...
}
~~~

It is crucial to define permissions; never do something like this:

~~~js
// *.telefunc.js
// Environment: Node.js

export async function executeQuery(query) {
  const result = await database.runSQL(query);
  return result;
};
~~~

Always remember that telefunctions are public: anyone in the world can call your telefunctions.

~~~js
// Environment: Anyone's browser dev console

// Anyone in the world can go to your website,
// open the browser's web dev console, and call your telefunctions.

const users = await server.executeQuery('SELECT login, password FROM users;');
users.forEach(({login, password}) => {
  // W00t I have all passwords ｡^‿^｡
  console.log(login, password);
});
~~~

You should `throw new Abort()` only for *unexpected* errors.
For expected errors return a JavaScript value instead.

~~~js
// *.telefunc.js
// Environment: Node.js

import { getContext } from 'telefunc'

export { getTodoList }
server.getTodoList = async function() {
  const isLoggedIn = getContext().user;
  // The user may not be logged in: this is an *expected* error.
  if( isLoggedIn ) {
    // Instead of `throw new Abort()` we return a plain JavaScript object `{ isNotLoggedIn: true }`.
    // The frontend can then for example redirect to the login page.
    return { isNotLoggedIn : true};
  }
  // ...
};
~~~

If your app is bug-free and no-one is trying to hack you, then nothing unexpected would happen, and your `throw new Abort()` will never be called.

You can think of `throw new Abort()` as a safeguard for bugs & hackers. For anything else return a JavaScript value.

That's why Telefunc only provides `Abort` and doesn't provide fine-grain exceptions (`NotLoggedIn`, `InvalidFormInput`, ...):
for expected errors, you return a plain JavaScript value instead of throwing exceptions.
